repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args: [ '--config', 'dagster/pyproject.toml' ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ '--profile', 'black' ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ '--config', 'dagster/.flake8' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-merge-conflict
      - id: check-yaml
        exclude: helm/.+/templates/.+
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args: [ '--verbose' ]
