apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dagster-webserver-hpa
  labels:
    app.kubernetes.io/name: dagster
    app.kubernetes.io/component: dagster
    app.kubernetes.io/part-of: giga-dataops-platform
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dagster-dagster-webserver
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dagster-oauth2-proxy-hpa
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: dagster
    app.kubernetes.io/part-of: giga-dataops-platform
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dagster-authproxy-oauth2-proxy
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
