apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stdin.yaml

patches:
  - path: patches/daemon-init-container-patch.yaml
    target:
      kind: Deployment
      name: dagster-daemon
  - path: patches/webserver-init-container-patch.yaml
    target:
      kind: Deployment
      name: dagster-dagster-webserver
