annotations:
  category: Database
  images: |
    - name: os-shell
      image: public.ecr.aws/bitnami/os-shell:11-debian-11-r91
    - name: redis-exporter
      image: public.ecr.aws/bitnami/redis-exporter:1.55.0-debian-11-r2
    - name: redis-sentinel
      image: public.ecr.aws/bitnami/redis-sentinel:7.2.3-debian-11-r1
    - name: redis
      image: public.ecr.aws/bitnami/redis:7.2.3-debian-11-r1
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.2.3
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: redis
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis
version: 18.3.2
